# Copyright 2020 The Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    app: ${NAME}
  name: ${NAME}-build
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${NAME}-artifacts
    labels:
      app: ${NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}-artifact-build
    labels:
      app: ${NAME}
      name: ${NAME}-artifact-build
  spec:
    successfulBuildsHistoryLimit: 1
    failedBuildsHistoryLimit: 1
    output:
      to:
        kind: ImageStreamTag 
        name: ${NAME}-artifacts:${OUTPUT_IMAGE_TAG}
    resources:
      limits:
        cpu: ${CPU_LIMIT}
        memory: ${MEMORY_LIMIT}
      requests:
        cpu: ${CPU_REQUEST}
        memory: ${MEMORY_REQUEST}
    runPolicy: Serial
    source:
      contextDir: ${SOURCE_CONTEXT_DIR}
      git:
        ref: ${GIT_REF}
        uri: ${GIT_REPO_URL}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: BUILD_LOGLEVEL
          value: "5"
        from:
          kind: ImageStreamTag
          name: ${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}
          namespace: ${SOURCE_IMAGE_NAMESPACE}
        incremental: false
      type: Source
    # triggers:
    # - type: ConfigChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}-image-build
    labels:
      app: ${NAME}
      name: ${NAME}-image-build
  spec:
    successfulBuildsHistoryLimit: 3
    failedBuildsHistoryLimit: 3
    output:
      to:
        kind: ImageStreamTag 
        name: ${NAME}:${OUTPUT_IMAGE_TAG}
    resources:
      limits:
        cpu: ${CPU_LIMIT}
        memory: ${MEMORY_LIMIT}
      requests:
        cpu: ${CPU_REQUEST}
        memory: ${MEMORY_REQUEST}
    runPolicy: Serial
    source:
      type: Dockerfile
      dockerfile: |-
        FROM image-registry.openshift-image-registry.svc:5000/04d1a3-tools/caddy-s2i-v2:latest
        COPY bcfoi/* /opt/app-root/src
        RUN ls -lah /opt/app-root/src
        CMD /usr/libexec/s2i/run
      images:
      - from: 
          kind: ImageStreamTag
          name: ${NAME}-artifacts:latest
        paths: 
        - sourcePath: /opt/app-root/src/dist/bcfoi
          destinationDir: "bcfoi"
    strategy:
      dockerStrategy:
        from: 
          kind: DockerImage
          name: image-registry.openshift-image-registry.svc:5000/04d1a3-tools/caddy-s2i-v2:latest
      type: Docker
      # triggers:
      #   - imageChange: {}
      #     type: ImageChange
parameters:
- description: |
    The name assigned to all of the objects defined in this template.
    You should keep this as default unless your know what your doing.
  displayName: Name
  name: NAME
  required: true
  value: web
- description: |
    The URL to your GIT repo, don't use the this default unless
    your just experimenting.
  displayName: Git Repo URL
  name: GIT_REPO_URL
  required: true
  value: https://github.com/bcgov/foi-requests.git
- description: The git reference or branch.
  displayName: Git Reference
  name: GIT_REF
  required: true
  value: master
- description: The source context directory.
  displayName: Source Context Directory
  name: SOURCE_CONTEXT_DIR
  required: false
  value: "web"
- description: The tag given to the built image.
  displayName: Output Image Tag
  name: OUTPUT_IMAGE_TAG
  required: true
  value: latest
- description: The openshift project where builds and target images are stored.
  displayName: Build Project
  name: SOURCE_IMAGE_NAMESPACE
  value: 'openshift'
  required: true
- description: The name of the source image.
  displayName: Source Image Name
  name: SOURCE_IMAGE_NAME
  value: 'nodejs'
  required: true
- description: The tag of the source image.
  displayName: Source Image Tag
  name: SOURCE_IMAGE_TAG
  value: "10"
  required: true
- description: The resources CPU limit (in cores) for this build.
  displayName: Resources CPU Limit
  name: CPU_LIMIT
  required: true
  value: "2"
- description: The resources Memory limit (in Mi, Gi, etc) for this build.
  displayName: Resources Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 4Gi
- description: The resources CPU request (in cores) for this build.
  displayName: Resources CPU Request
  name: CPU_REQUEST
  required: true
  value: "1"
- description: The resources Memory request (in Mi, Gi, etc) for this build.
  displayName: Resources Memory Request
  name: MEMORY_REQUEST
  required: true
  value: 2Gi
