name: Deploy web to dev


on:
  push:
    branches:
      - dev
    paths:
      - "web/**"
      - ".github/workflows/web-cd.dev.yml"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (dev/test/prod)"
        required: true
        default: "dev"

defaults:
  run:
    shell: bash
    working-directory: ./web

env:
  APP_NAME: "web"
  TAG_NAME: "dev"

jobs:
  web-cd-by-push:
    runs-on: ubuntu-24.04

    if: github.event_name == 'push' && github.repository == 'bcgov/foi-requests'
    environment:
      name: "dev"

    steps:
       # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      # Login to BC Gov Docker Image Repository
      - name: Login to Openshift Docker
        run : |
         docker login ${{ secrets.PUBLIC_IMAGE_REPOSITORY }} -u ${{ secrets.OPENSHIFT_SA_NAME }} -p ${{ secrets.OPENSHIFT_SA_TOOLS_TOKEN }}

      # Build the APP image
      - name: Build APP Image
        run: |
          docker build -t ${{ secrets.PUBLIC_IMAGE_REPOSITORY }}/${{ secrets.OPENSHIFT_NAMESPACE }}-tools/web:latest -f Dockerfile .

      # Push the APP image
      - name: Push APP Image
        run: |
          docker push ${{ secrets.PUBLIC_IMAGE_REPOSITORY }}/${{ secrets.OPENSHIFT_NAMESPACE }}-tools/web:latest

      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '4.6'

      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '4.6'
        
      - name: Login Openshift
        shell: bash
        run: |
          oc login --server=${{secrets.OPENSHIFT4_LOGIN_REGISTRY}} --token=${{secrets.OPENSHIFT4_SA_TOKEN}}

      - name: Tag+Deploy for dev
        shell: bash
        run: |
          oc project ${{ secrets.OPENSHIFT_NAMESPACE }}-tools
          oc tag web:latest web:${{ env.TAG_NAME }}
      
      - name: Rollout Restart Deployment
        shell: bash
        run: |
          oc project ${{ secrets.OPENSHIFT_NAMESPACE }}-dev
          oc rollout restart deployment/web
